using Esolang.Generator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Esolang.Brainfuck.Generator;

/// <summary>
/// A source generator that emits method implementations from <c>GenerateBrainfuckMethodAttribute</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public partial class MethodGenerator : IIncrementalGenerator
{
    /// <summary>
    /// The standard auto-generated file header.
    /// </summary>
    public const string CommentAutoGenerated = "// <auto-generated/>";

    /// <summary>
    /// The namespace where the generated attribute is placed.
    /// </summary>
    public const string NameSpaceName = "Esolang.Brainfuck";

    /// <summary>
    /// The generated attribute class name.
    /// </summary>
    public const string ClassNameBrainfuckAttribution = "GenerateBrainfuckMethodAttribute";

    /// <summary>
    /// The source file name used to aggregate generated methods.
    /// </summary>
    public const string GeneratedMethodsFileName = "GenerateBrainfuckMethod.g.cs";

    const string GeneratedMethodsFileHeader = $$"""
        {{CommentAutoGenerated}}
        #nullable enable
        #pragma warning disable CS0219
        #pragma warning disable CS1998

        """;
    const string ListDummyDeclaration = $$"""
        namespace Esolang.Brainfuck.__Generated {
            internal static class ListDummyHelper {
                internal class ListDummy<T> { internal T[] Items = default!; }
            }
        }
        """;
    const string LoggerUtilityDeclaration = $$"""
        namespace Esolang.Brainfuck.__Generated {
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            internal static class LoggerUtilities
            {
                private static readonly global::System.Action<global::Microsoft.Extensions.Logging.ILogger, int, char, int, byte, global::System.Exception?> ExecutingCommand =
                    global::Microsoft.Extensions.Logging.LoggerMessage.Define<int, char, int, byte>(
                        global::Microsoft.Extensions.Logging.LogLevel.Trace,
                        new global::Microsoft.Extensions.Logging.EventId(1, "ExecutingCommand"),
                        "IP {IP}: '{Command}' [Pointer: {Pointer}, Value: {Value}]");

                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                public static void LogInstruction(global::Microsoft.Extensions.Logging.ILogger? logger, int ip, char command, int pointer, byte value)
                {
                    if (logger is null || !logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Trace)) return;
                    ExecutingCommand(logger, ip, command, pointer, value, null);
                }
            }
        }
        """;
    [Flags]
    enum RuntimeFacadeFeatures
    {
        None = 0,
        UseListAsMemory = 1 << 0,
        UseLogger = 1 << 1,
    }

    readonly record struct EmittedMethod(string Source, RuntimeFacadeFeatures Features);

    /// <summary>
    /// Initializes the generator and registers the attribute and method generation pipeline.
    /// </summary>
    /// <param name="context">The initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
            context.AddSource("GenerateBrainfuckMethodAttribute.cs", $$"""
                {{CommentAutoGenerated}}
                using System;
                using System.Diagnostics;
                namespace {{NameSpaceName}} {
                    [Conditional("COMPILE_TIME_ONLY")]
                    [AttributeUsage(AttributeTargets.Method, AllowMultiple =false, Inherited = false)]
                    internal sealed class {{ClassNameBrainfuckAttribution}} : Attribute
                    {
                        /// <summary>
                        /// generate brainfuck method.
                        /// </summary>
                        /// <param name="source">brainfuck source.</param>
                        internal {{ClassNameBrainfuckAttribution}}(string source) { }
                        /// <summary>Increment the data pointer by one (to point to the next cell to the right).</summary>
                        public string {{nameof(BrainfuckOptions.IncrementPointer)}} = "{{BrainfuckOptionsDefault.IncrementPointer}}";
                        /// <summary>Decrement the data pointer by one (to point to the next cell to the left).</summary>
                        public string {{nameof(BrainfuckOptions.DecrementPointer)}} = "{{BrainfuckOptionsDefault.DecrementPointer}}";
                        /// <summary>Increment the byte at the data pointer by one.</summary>
                        public string {{nameof(BrainfuckOptions.IncrementCurrent)}} = "{{BrainfuckOptionsDefault.IncrementCurrent}}";
                        /// <summary>Decrement the byte at the data pointer by one.</summary>
                        public string {{nameof(BrainfuckOptions.DecrementCurrent)}} = "{{BrainfuckOptionsDefault.DecrementCurrent}}";
                        /// <summary>Output the byte at the data pointer.</summary>
                        public string {{nameof(BrainfuckOptions.Output)}} = "{{BrainfuckOptionsDefault.Output}}";
                        /// <summary>Accept one byte of input, storing its value in the byte at the data pointer.</summary>
                        public string {{nameof(BrainfuckOptions.Input)}} = "{{BrainfuckOptionsDefault.Input}}";
                        /// <summary>If the byte at the data pointer is zero, then instead of moving the instruction pointer forward to the next command, jump it forward to the command after the matching ] command.</summary>
                        public string {{nameof(BrainfuckOptions.Begin)}} = "{{BrainfuckOptionsDefault.Begin}}";
                        /// <summary>If the byte at the data pointer is nonzero, then instead of moving the instruction pointer forward to the next command, jump it back to the command after the matching [ command.</summary>
                        public string {{nameof(BrainfuckOptions.End)}} = "{{BrainfuckOptionsDefault.End}}";
                    }
                }
                """));
        const string attributeNameSpaceName = NameSpaceName + ".GenerateBrainfuckMethodAttribute";
        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            attributeNameSpaceName,
            static (node, token) => true,
            static (context, token) => context
        );

        var generatedTargets = source.Collect();
        var languageVersion = context.ParseOptionsProvider
            .Select(static (parseOptions, token) =>
                parseOptions is CSharpParseOptions csharpParseOptions
                    ? csharpParseOptions.LanguageVersion
                    : LanguageVersion.Default);
        var compilation = context.CompilationProvider;
        var knownTypes = compilation.Select(static (c, _) => new KnownTypes(c));
        var generationInputs = generatedTargets.Combine(languageVersion).Combine(compilation).Combine(knownTypes);

        context.RegisterSourceOutput(generationInputs, static (context, input) =>
        {
            var (((sources, currentLanguageVersion), compilation), types) = input;

            if (sources.IsDefaultOrEmpty)
                return;

            var builder = new System.Text.StringBuilder();
            var features = RuntimeFacadeFeatures.None;
            foreach (var source in sources)
            {
                var methodSymbol = (IMethodSymbol)source.TargetSymbol;
                if (!methodSymbol.IsPartialDefinition)
                {
                    context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.MethodMustBePartial, methodSymbol.Locations[0], methodSymbol.Name));
                    continue;
                }

                var generated = Emit(context, source, currentLanguageVersion, compilation, types);
                if (generated is not { } method)
                    continue;

                if (builder.Length == 0)
                    builder.Append(GeneratedMethodsFileHeader);
                else
                    builder.Append("\n\n");
                builder.Append(method.Source);
                features |= method.Features;
            }

            if (features.HasFlag(RuntimeFacadeFeatures.UseListAsMemory))
            {
                if (builder.Length > 0)
                    builder.Append("\n\n");
                builder.Append(ListDummyDeclaration);
            }

            if (features.HasFlag(RuntimeFacadeFeatures.UseLogger))
            {
                if (builder.Length > 0)
                    builder.Append("\n\n");
                builder.Append(LoggerUtilityDeclaration);
            }

            if (builder.Length > 0)
                context.AddSource(GeneratedMethodsFileName, builder.ToString());
        });
    }
}
