using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Esolang.Brainfuck.Generator;

/// <summary>
/// A source generator that emits method implementations from <c>GenerateBrainfuckMethodAttribute</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public partial class MethodGenerator : IIncrementalGenerator
{
    /// <summary>
    /// The standard auto-generated file header.
    /// </summary>
    public const string CommentAutoGenerated = "// <auto-generated/>";

    /// <summary>
    /// The namespace where the generated attribute is placed.
    /// </summary>
    public const string NameSpaceName = "Esolang.Brainfuck";

    /// <summary>
    /// The generated attribute class name.
    /// </summary>
    public const string ClassNameBrainfuckAttribution = "GenerateBrainfuckMethodAttribute";

    /// <summary>
    /// The source file name used to aggregate generated methods.
    /// </summary>
    public const string GeneratedMethodsFileName = "GenerateBrainfuckMethod.g.cs";

    readonly struct KnownTypes
    {
        public readonly INamedTypeSymbol? String;
        public readonly INamedTypeSymbol? Task;
        public readonly INamedTypeSymbol? TaskInt;
        public readonly INamedTypeSymbol? TaskString;
        public readonly INamedTypeSymbol? ValueTask;
        public readonly INamedTypeSymbol? ValueTaskInt;
        public readonly INamedTypeSymbol? ValueTaskString;
        public readonly INamedTypeSymbol? IEnumerableByte;
        public readonly INamedTypeSymbol? IAsyncEnumerableByte;
        public readonly INamedTypeSymbol? PipeReader;
        public readonly INamedTypeSymbol? PipeWriter;
        public readonly INamedTypeSymbol? TextReader;
        public readonly INamedTypeSymbol? TextWriter;
        public readonly INamedTypeSymbol? CancellationToken;
        public readonly INamedTypeSymbol? ILogger;
        public readonly INamedTypeSymbol? ILoggerT;

        public KnownTypes(Compilation compilation)
        {
            String = compilation.GetSpecialType(SpecialType.System_String);
            var byteSymbol = compilation.GetSpecialType(SpecialType.System_Byte);
            var intSymbol = compilation.GetSpecialType(SpecialType.System_Int32);

            var taskGeneric = GetBestTypeByMetadataName(compilation, "System.Threading.Tasks.Task`1");
            Task = GetBestTypeByMetadataName(compilation, "System.Threading.Tasks.Task");
            TaskInt = taskGeneric?.Construct(intSymbol);
            TaskString = taskGeneric?.Construct(String);

            var valueTaskGeneric = GetBestTypeByMetadataName(compilation, "System.Threading.Tasks.ValueTask`1");
            ValueTask = GetBestTypeByMetadataName(compilation, "System.Threading.Tasks.ValueTask");
            ValueTaskInt = valueTaskGeneric?.Construct(intSymbol);
            ValueTaskString = valueTaskGeneric?.Construct(String);

            var enumerableGeneric = GetBestTypeByMetadataName(compilation, "System.Collections.Generic.IEnumerable`1");
            IEnumerableByte = enumerableGeneric?.Construct(byteSymbol);

            var asyncEnumerableGeneric = GetBestTypeByMetadataName(compilation, "System.Collections.Generic.IAsyncEnumerable`1");
            IAsyncEnumerableByte = asyncEnumerableGeneric?.Construct(byteSymbol);

            PipeReader = GetBestTypeByMetadataName(compilation, "System.IO.Pipelines.PipeReader");
            PipeWriter = GetBestTypeByMetadataName(compilation, "System.IO.Pipelines.PipeWriter");
            TextReader = GetBestTypeByMetadataName(compilation, "System.IO.TextReader");
            TextWriter = GetBestTypeByMetadataName(compilation, "System.IO.TextWriter");
            CancellationToken = GetBestTypeByMetadataName(compilation, "System.Threading.CancellationToken");
            ILogger = GetBestTypeByMetadataName(compilation, "Microsoft.Extensions.Logging.ILogger");
            ILoggerT = GetBestTypeByMetadataName(compilation, "Microsoft.Extensions.Logging.ILogger`1");
        }

        private static INamedTypeSymbol? GetBestTypeByMetadataName(Compilation compilation, string metadataName)
        {
            var type = compilation.GetTypeByMetadataName(metadataName);
            if (type != null) return type;

            foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
            {
                var found = assembly.GetTypeByMetadataName(metadataName);
                if (found != null) return found;
            }
            return null;
        }
    }

    const string GeneratedMethodsFileHeader = $$"""
        {{CommentAutoGenerated}}
        #nullable enable
        #pragma warning disable CS0219
        #pragma warning disable CS1998

        """;
    const string ListDummyDeclaration = "file class ListDummy<T> { internal T[] Items = default!; }";
    [Flags]
    enum RuntimeFacadeFeatures
    {
        None = 0,
        UseListAsMemory = 1 << 0,
        UseLogger = 1 << 1,
    }

    readonly record struct EmittedMethod(string Source, RuntimeFacadeFeatures Features);

    /// <summary>
    /// Initializes the generator and registers the attribute and method generation pipeline.
    /// </summary>
    /// <param name="context">The initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
            context.AddSource("GenerateBrainfuckMethodAttribute.cs", $$"""
                {{CommentAutoGenerated}}
                using System;
                using System.Diagnostics;
                namespace {{NameSpaceName}} {
                    [Conditional("COMPILE_TIME_ONLY")]
                    [AttributeUsage(AttributeTargets.Method, AllowMultiple =false, Inherited = false)]
                    internal sealed class {{ClassNameBrainfuckAttribution}} : Attribute
                    {
                        /// <summary>
                        /// generate brainfuck method.
                        /// </summary>
                        /// <param name="source">brainfuck source.</param>
                        internal {{ClassNameBrainfuckAttribution}}(string source) { }
                        /// <summary>Increment the data pointer by one (to point to the next cell to the right).</summary>
                        public string {{nameof(BrainfuckOptions.IncrementPointer)}} = "{{BrainfuckOptionsDefault.IncrementPointer}}";
                        /// <summary>Decrement the data pointer by one (to point to the next cell to the left).</summary>
                        public string {{nameof(BrainfuckOptions.DecrementPointer)}} = "{{BrainfuckOptionsDefault.DecrementPointer}}";
                        /// <summary>Increment the byte at the data pointer by one.</summary>
                        public string {{nameof(BrainfuckOptions.IncrementCurrent)}} = "{{BrainfuckOptionsDefault.IncrementCurrent}}";
                        /// <summary>Decrement the byte at the data pointer by one.</summary>
                        public string {{nameof(BrainfuckOptions.DecrementCurrent)}} = "{{BrainfuckOptionsDefault.DecrementCurrent}}";
                        /// <summary>Output the byte at the data pointer.</summary>
                        public string {{nameof(BrainfuckOptions.Output)}} = "{{BrainfuckOptionsDefault.Output}}";
                        /// <summary>Accept one byte of input, storing its value in the byte at the data pointer.</summary>
                        public string {{nameof(BrainfuckOptions.Input)}} = "{{BrainfuckOptionsDefault.Input}}";
                        /// <summary>If the byte at the data pointer is zero, then instead of moving the instruction pointer forward to the next command, jump it forward to the command after the matching ] command.</summary>
                        public string {{nameof(BrainfuckOptions.Begin)}} = "{{BrainfuckOptionsDefault.Begin}}";
                        /// <summary>If the byte at the data pointer is nonzero, then instead of moving the instruction pointer forward to the next command, jump it back to the command after the matching [ command.</summary>
                        public string {{nameof(BrainfuckOptions.End)}} = "{{BrainfuckOptionsDefault.End}}";
                    }
                }
                """));
        const string attributeNameSpaceName = NameSpaceName + ".GenerateBrainfuckMethodAttribute";
        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            attributeNameSpaceName,
            static (node, token) => true,
            static (context, token) => context
        );

        var generatedTargets = source.Collect();
        var languageVersion = context.ParseOptionsProvider
            .Select(static (parseOptions, token) =>
                parseOptions is CSharpParseOptions csharpParseOptions
                    ? csharpParseOptions.LanguageVersion
                    : LanguageVersion.Default);
        var compilation = context.CompilationProvider;
        var knownTypes = compilation.Select(static (c, _) => new KnownTypes(c));
        var generationInputs = generatedTargets.Combine(languageVersion).Combine(compilation).Combine(knownTypes);

        context.RegisterSourceOutput(generationInputs, static (context, input) =>
        {
            var (((sources, currentLanguageVersion), compilation), types) = input;

            if (sources.IsDefaultOrEmpty)
                return;

            var builder = new System.Text.StringBuilder();
            var features = RuntimeFacadeFeatures.None;
            foreach (var source in sources)
            {
                var generated = Emit(context, source, currentLanguageVersion, compilation, types);
                if (generated is not { } method)
                    continue;

                if (builder.Length == 0)
                    builder.Append(GeneratedMethodsFileHeader);
                else
                    builder.Append("\n\n");
                builder.Append(method.Source);
                features |= method.Features;
            }

            if (features.HasFlag(RuntimeFacadeFeatures.UseListAsMemory))
            {
                if (builder.Length > 0)
                    builder.Append("\n\n");
                builder.Append(ListDummyDeclaration);
            }

            if (builder.Length > 0)
                context.AddSource(GeneratedMethodsFileName, builder.ToString());
        });
    }
}
