<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Esolang.Brainfuck.Interpreter.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Interpreter\Esolang.Brainfuck.Interpreter.csproj" />
  </ItemGroup>

</Project>
