<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>dotnet-brainfuck</AssemblyName>
    <Title>brainfuck console.</Title>
    <PublishRelease>true</PublishRelease>
    <IsPublishable>true</IsPublishable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>dotnet-brainfuck</ToolCommandName>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>esolang;brainfuck;interpreter;cli;dotnet-tool</PackageTags>
    <IsAotCompatible>true</IsAotCompatible>
    <StripSymbols>false</StripSymbols>
    <VerifyReferenceAotCompatibility>false</VerifyReferenceAotCompatibility>
    <PublishAot>true</PublishAot>
    <ToolPackageRuntimeIdentifiers>win-x64;linux-x64;osx-arm64;any</ToolPackageRuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Esolang.Interpreter.Abstractions" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Processor\Esolang.Brainfuck.Processor.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include ="Esolang.Brainfuck.Interpreter.Tests"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="./README.md" Pack="true" PackagePath="\" />
    <None Include="../CHANGELOG.md" Pack="true" PackagePath="\" />
    <None Include="../LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
